apiVersion: v1
kind: Pod
metadata:
  name: coursecatalogue
  labels:
    app: coursecatalogue
spec:
  containers:
    - name: coursecatalogue
      image: coursecatalogue.azurecr.io/tai-coursecatalogue:0.0.1
      resources:
        requests:
          cpu: "500m"
          memory: "400Mi"
        limits:
          cpu: "1000m"
          memory: "800Mi"
      envFrom:
      - configMapRef:
          name: envs
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      imagePullPolicy: Always